name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - run: npm install

      - name: Run typecheck
        uses: actions/setup-node@v2
      - run: npm run check-types

      - name: Run linter
        uses: actions/setup-node@v2
      - run: npm run lint
