name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 14.x
          cache: npm

      - name: Setup node 14
        run: npm install

      - name: Run typecheck
        run: npm run check-types

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test:coverage
