name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v2
        with:
          node-version: 14.x
          cache: npm

      - name: install dependencies
      - run: npm install

      - name: run typechecks
      - run: npm run check-types

      - name: run linter
      - run: npm run lint
